house.power.consumption <- read.table(file="household_power_consumption.txt", sep=";", quote="\"", header = T, na.strings = "?")
house.power.consumption <- subset(house.power.consumption, Date == "1/2/2007" | Date == "2/2/2007")
house.power.consumption$Time <- strptime(paste0(house.power.consumption$Date,house.power.consumption$Time, sep=" "), "%d/%m/%Y %H:%M:%S")
house.power.consumption$Date <- as.Date(house.power.consumption$Date,format="%d/%m/%Y")

png(filename = "plot4.png", width = 480, height = 480, units = "px")
par(mfrow=c(2,2))
plot(house.power.consumption$Time,house.power.consumption$Global_active_power, ylab="Global Active Power",xlab="", pch=20, type="l")
plot(house.power.consumption$Time,house.power.consumption$Voltage, ylab="Voltage",xlab="datetime", pch=20, type="l")
plot(house.power.consumption$Time, house.power.consumption$Sub_metering_1, ylab="Energy sub metering",xlab="", pch=20, type="n")
points(house.power.consumption$Time, house.power.consumption$Sub_metering_1,  pch=20, type="l", col="black")
points(house.power.consumption$Time, house.power.consumption$Sub_metering_2,  pch=20, type="l", col="red")
points(house.power.consumption$Time, house.power.consumption$Sub_metering_3,  pch=20, type="l", col="blue")
legend("topright",grep("Sub_metering_", names(house.power.consumption), value = T) ,col=c("black","red","blue"),lty=1)
plot(house.power.consumption$Time,house.power.consumption$Global_reactive_power, ylab="Global_reactive_power",xlab="datetime", pch=20, type="l")
dev.off()